py.test support: Better output for `assert stbt.match(...)`
Instead of:

    def test_that_fails():
    >       assert stbt.match("template.png")
    E       assert <stbt.MatchResult object at 0x106db0450>

We get:

    def test_that_fails():
    >       assert stbt.match("template.png")
    E       assert MatchResult(timestamp=269493666, match=False,
                region=Region(x=180, y=0, width=...=160),
                first_pass_result=0.573794186115,
                frame=320x240x3, image="template.png")