stbt-run: Fix formatting of IOError exceptions
Previously code like:

    open('non-existent')

would print the error:

    IOError: '2'

because 2 is `errno.ENOENT`.  Now it prints:

    IOError: [Errno 2] No such file or directory: 'non-existent'

which is the same that Python would print.